### ISSUE TITLE
Migrate to a Homebrew tap command

### ISSUE THREAD

**Issue by mikemcquaid** [andrew/homebrew-brewdler#27]
If you put a `brew-brewdler.rb` or similarly named file in the `cmd` directory of a tap then you can call it with `brew brewdler` without having to add it to the `PATH`, install it with RubyGems or any of that jazz. It'll also be kept up-to-date automatically with `brew update`. 

Seems to me this could be a pretty neat deployment method as it wouldn't require any installation beyond a `brew tap andrew/homebrew-brewdler`. The only downside is that using Bundler and Gem dependencies is trickier. Taking a brief look at the code I reckon this project could get away with no runtime Gem dependencies.

Thoughts? If you're extremely :-1: on this I'm happy to close out. Otherwise would be great if anyone wanted to pick this up (and if they didn't, I will). I'm also happy to get this moved to the Homebrew organisation and bless it as the "official" solution.

Thanks again @andrew and others!

**Comment by andrew** [comment]
I think that sounds like a great idea @mikemcquaid :+1: 

As you said, we can easily drop the two dependencies, I'd also like to get rid of the `eval` bit before we introduce it to a wider audience!

**Comment by andrew** [comment]
Also happy to move it to the @Homebrew org, would likely help keep it better maintained :bow:

**Comment by andrew** [comment]
Fixed by https://github.com/andrew/homebrew-brewdler/pull/28
